### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by mgroth0** [saadq/ClearConsole#1]
'Clear Console' command appears (with shortcut alt-K) but hitting enter does not do anything. I expected console to print a bunch of blank lines but instead it did nothing.

**Comment by saadq** [comment]
Thanks for bringing this up. I haven't been using Sublime for awhile now, but I just verified this issue. Something may have changed within Sublime's plugin API, I'll have to look into it.

**Comment by saadq** [comment]
Actually scratch that - Are you sure this issue exists? When you open up the console manually with <kbd>Ctrl</kbd>+<kbd>\`</kbd>, and then use the `'Clear Console'` command, it seems to work for me. It might be possible that you're mixing up the developer console with the stdout output that comes when you run a program or something. Let me know if this isn't the case.

**Comment by mgroth0** [comment]
Weirdly enough it is working for me now too, but feel like I took the same exact steps!

**Comment by saadq** [comment]
Hey @mgroth0, I think based on your comment that the issue was resolved, but feel free to open if this isn't the case.
